name: Déploiement Angular vers GitHub Pages

on:
  push:
    branches:
      - main # ou master, selon ta branche par défaut

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Utiliser Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Installer les dépendances
        run: npm install

      - name: Construire le projet Angular
        run: npm run build -- --configuration=production

      - name: Déployer vers GitHub Pages
        run: npx angular-cli-ghpages --dir=dist/tester-a11y-angular
